#!/bin/sh

function i3() {

  git clone https://github.com/ubikOne/i3-setup.git eos-i3
  cd eos-i3
  cp -R .config/* ~/.config/
  sudo cp .wallpapers/dune.jpg /usr/share/endeavouros/backgrounds/
  mkdir ~/.screensaver
  cp .wallpapers/dune.jpg ~/.screensaver/
  chmod -R +x ~/.config/i3/scripts
  cp .Xresources ~/
  cp .gtkrc-2.0 ~/
  cp .moc -R ~/.moc
  yay -S --needed --noconfirm - < packages-repository.txt
  cd ..
  
}

function dm() {

  git clone https://github.com/nullgemm/ly.git
  cd ly
  make github
  make
  sudo make install
  sudo systemctl enable ly.service
  sudo systemctl disable getty@tty2.service
  cd ..
  sudo rm -R ly

}

function emacs() {

  git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
  ~/.emacs.d/bin/doom -y install
  cp -R .doom.d/* ~/.doom.d/
  .emacs.d/bin/doom sync

}

function lock() {

  cp /usr/share/doc/betterlockscreen/examples/betterlockscreenrc ~/.config
#  betterlockscreen -u ~/.screensaver/dune.jpg

}

function matterhorn() {

  git clone https://aur.archlinux.org/ncurses5-compat-libs.git
  cd ncurses5-compat-libs
  makepkg -si --skippgpcheck --noconfirm
  yay -S --noconfirm matterhorn-bin
  cd ..
  sudo rm -R ncurses5-compat-libs

}

function vim() {
  sh -c "$(curl -fsSL https://gitlab.com/ubikOne/vim-config/raw/master/install)"
}

function main() {

  cd ~/.config

  yay --noconfirm
  i3
  pip install i3ipc
  dm
  lock
  matterhorn
  vim
  emacs

}

main
