#!/bin/bash

##### menu #############################################################################

super + @space
      rofi -modi drun -show drun -line-padding 4 \
      -columns 2 -padding 50 -hide-scrollbar \
      -show-icons -drun-icon-theme "Papirus" -font "Mononoki Bold Italic 10"
      
super + ctrl + @space
      rofi -modi drun -show window -line-padding 4 \
      -columns 2 -padding 50 -hide-scrollbar \
      -show-icons -drun-icon-theme "Papirus" -font "Mononoki Bold Italic 10"
      
super + alt + @space
      rofi -modi drun -show ssh -line-padding 4 \
      -columns 2 -padding 50 -hide-scrollbar \
      -show-icons -drun-icon-theme "Papirus" -font "Mononoki Bold Italic 10"
      
super + alt + ctrl + @space
      dmenu_run

########################################################################################

###### system ##########################################################################

# lock
super + l
      betterlockscreen -l dimblur

# session
control + shift + e
      ~/.config/i3/scripts/shutdown_menu
      
########################################################################################
      
###### windows #########################################################################

# close window
super + c
      i3-msg kill window

# 'Minimize' / move windows to scratchpad
super + m
      i3-msg move scratchpad

# Cycle through 'minimized' windows
super + alt + m
      i3-msg scratchpad show

# Change focus / move focused window
super + {_,shift +}{h,j,k,l}
      i3-msg {focus,move}{left,down,up,right}

super + {_,shift +}{Left,Down,Up,Right}
      i3-msg {focus,move}{left,down,up,right}

# Change container layout (stacked, tabbed, toggle split)
super + {s,w,e}
      i3-msg layout {stacked, tabbed, toggle}
      
########################################################################################      

###### apllications ####################################################################

super + Return
      alacritty

super + alt + m
      thunderbird
      
super + alt + w
      firefox
      
super + alt + f
      thunar

super + shift + m
      alacritty -t matterhorn -e "matterhorn"

super + shift + n
      alacritty -t ranger -e "ranger"

super + shift + a
      alacritty -t alsamixer -e "alsamixer"

super + shift + b
      alacritty -t bmon -e "bmon"

super + shift + v
      alacritty -t wavemon -e "wavemon"

super + shift + p
      alacritty -t mocp -e $SHELL -c "mocp -T ~/.moc/themes/nightly_enhanced"
      
########################################################################################
      
###### sxhkd ###########################################################################

# make sxhkd reload its configuration files:
super + Escape
      pkill -USR1 -x sxhkd

########################################################################################

###### others ##########################################################################

# cheatsheet      
super + F1
      alacritty -t cheatsheet -e $SHELL -c 'glow -p -w 80 ~/.config/i3/keybindings.md'

super + F9
      mocp --previous

super + F10
      mocp --toogle-pause

super + F11
      mocp --stop

super + F9
      mocp --next

# printscreen
Print
      flameshot gui

super + Print
      flameshot full
      
super + a
      /usr/local/bin/switch-audio-port

########################################################################################

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}
